### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pvlrmnnk** [AlexeyBoldakov/StatusCal#1]
This isn't fair. I think you should return Emil Kreutzman as an author of the original app. 

[link](https://github.com/AlexeyBoldakov/StatusCal/commit/4c13f83be8e5f211778599b57f97b3d4896cfc19)

**Comment by pvlrmnnk** [comment]
You both did a great job.

**Comment by AlexeyBoldakov** [comment]
Yes, thanks, you're right. I will return the author with the release of the next version.
